networks:
  network2:
    name: network2
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/public_html
    networks:
      - network2
    depends_on:
      - php
      - mysql

  php:
    container_name: php
    build:
      ./images/php
    volumes:
      - ./www:/var/www/public_html
    networks:
      - network2
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network2

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 1500:80
    environment:
      - PMA_HOST=mysql
    networks:
      - network2
    depends_on:
      - mysql